ktor:
  application:
    modules:
      - io.github.tuguzt.professional.app.ApplicationKt.module
  deployment:
    port: 8080
database:
  uri: "$DATABASE_URI:jdbc:h2:file:./build/db"
  driver: "$DATABASE_DRIVER:org.h2.Driver"
